name: Deploy to App Engine on merge
on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: ${{ secrets.DEV_PROJECT_ID }}
  REGION: ${{ secrets.GAR_REGION }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
  IMAGE_NAME: cafeteller/api

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest .

      # Step 4: Push Docker image to Amazon ECR
      - name: Tag Docker image
        run: |
          docker tag cafeteller/api:latest asia-southeast1-docker.pkg.dev/cafeteller-f18b8/api/cafeteller/api:latest
          docker tag cafeteller/api:latest asia-southeast1-docker.pkg.dev/cafeteller-f18b8/api/cafeteller/api:v0.1.0

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Push Docker image to Artifact Registry
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/cafeteller-f18b8/api/cafeteller/api:latest
